### ISSUE TITLE
Issue  - Q. How to use data- attribute in html5?

### ISSUE THREAD

**Issue by intend-dev** [learning-zone/HTML#1]
Fixed code since getElementById is not working

According to mdn we can use querySelector -
    -> https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
    

```js
const article = document.querySelector("#electric-cars");

article.dataset.columns; // "10"
article.dataset.indexNumber; // "100"
article.dataset.parent; // "cars"
```

**Comment by learning-zone** [comment]
Thanks for creating issue, Code has been updated now.
