### ISSUE TITLE
Issue with HTML5 Canvas Code

### ISSUE THREAD

**Issue by Hakim-CS** [learning-zone/HTML#8]
Description:
The provided HTML code contains examples of various shapes drawn using HTML5 Canvas. While the code demonstrates how to draw text, lines, rectangles, and circles on a canvas, there are several issues and improvements that can be addressed:

Inconsistent Naming: The canvas elements are named inconsistently (e.g., "text", "line", "rectangle", "rect", "circle"). Consistent naming conventions should be used to improve readability and maintainability.

Canvas Size: The canvas element for the "line" shape has its height set to 0, which results in a line not being visible. The canvas size should be adjusted to display the line properly.

Error Handling: The canvas elements for "rectangle" and "circle" have fallback text ("This browser does not support Canvas!"), but no such fallback is provided for the "text" and "line" elements. Consistent error handling should be implemented for all canvas elements.

**Comment by learning-zone** [comment]
I would prefer new PR instead. Thanks

**Comment by Hakim-CS** [comment]
thanks  a lot .
